[theme]
primaryColor="#5C6BC0"  # Indigo 400
backgroundColor="#060d1f"  # Deep space dark blue
secondaryBackgroundColor="#0b1326"  # Faded space blue
textColor="#dfe2f0"  # Soft white blue
font="serif"
